# Generated by Django 5.0.6 on 2024-10-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ("name",)},
        ),
    ]
